### ISSUE TITLE
Building on Debian

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#8]
I'm unable to build on Debian on linode.  Useful system stuff:

```
hostname = localhost
uname -m = x86_64
uname -r = 4.19.0-11-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.19.146-1 (2020-09-17)

gcc (Debian 8.3.0-6) 8.3.0
```

"configure" seems to run fine, but "make" hits a boatload of compile warnings but at least one error:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdl
 -g -O2 -MT comsys.lo -MD -MP -MF .deps/comsys.Tpo -c comsys.c  -fPIC -DPIC -o .
libs/comsys.o
comsys.c:59:31: error: ‘cf_string’ undeclared here (not in a function)
     {(char *)"guests_calias", cf_string, CA_STATIC, CA_PUBLIC, (int *)&mod_coms
ys_config.guests_calias, SBUF_SIZE},
                               ^~~~~~~~~
```

I reconfigured with --enable-module-comsys=no to see if I could get around this one error and recompiled... still erroring out:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdl
 -g -O2 -MT mail.lo -MD -MP -MF .deps/mail.Tpo -c mail.c  -fPIC -DPIC -o .libs/m
ail.o
mail.c:88:33: error: ‘cf_int’ undeclared here (not in a function); did you mean 
‘u_int’?
     {(char *)"mail_expiration", cf_int, CA_GOD, CA_PUBLIC, &mod_mail_config.mai
l_expiration, 0},
                                 ^~~~~~
                                 u_int
```

Reconfigured without either comsys or mail modules... (./configure --enable-module-comsys=no --enable-module-mail=no) and recompiled...

```
alloc.c: At top level:
alloc.c:218:11: error: conflicting types for ‘__xfind’
 MEMTRACK *__xfind(void *ptr)
           ^~~~~~~
alloc.c:170:12: note: previous implicit declaration of ‘__xfind’ was here
     mtrk = __xfind(ptr);
            ^~~~~~~
```

**Comment by EddyBeaupre** [comment]
Related to the new memory manager. Work in progress, should be fixed in Alpha 12.

**Comment by EddyBeaupre** [comment]
Please try now. It should work.

See the updated readme.md for build instructions.

**Comment by adamdray** [comment]
Rebuilt using instructions in README.me including "autoreconf -ivf" step.

First got an error that README wasn't there, so I 'touch'ed it and ran it again.

Then got tons of warnings. Reconfigured with CFLAGS=-w and ran make again.

Then got this error:

`
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdo
comsys.c:59:31: error: ‘cf_string’ undeclared here (not in a function)
   59 |     {(char *)"guests_calias", cf_string, CA_STATIC, CA_PUBLIC, (int *)&,
`

Reconfigured with mail and comsys modules disabled and ran make again. Got this error:

`
alloc.c:224:11: error: conflicting types for ‘__xfind’
  224 | MEMTRACK *__xfind(void *ptr)
      |           ^~~~~~~
alloc.c:176:12: note: previous implicit declaration of ‘__xfind’ was here
  176 |     mtrk = __xfind(ptr);
      |            ^~~~~~~
`

**Comment by EddyBeaupre** [comment]
Hi,

Fixed the README issue.

For the other issues, i can't reproduce it. Just tried on a clean Ubuntu server 20.04.1 LTS and i got no warning or errors at all.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-23 17 h 19 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Eddy Beaupré <eddy@beaupre.biz>, State change <state_change@noreply.github.com>
Objet : Re: [TinyMUSH/TinyMUSH] Building on Debian (#8)


Rebuilt using instructions in README.me including "autoreconf -ivf" step.

First got an error that README wasn't there, so I 'touch'ed it and ran it again.

Then got tons of warnings. Reconfigured with CFLAGS=-w and ran make again.

Then got this error:

libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdo comsys.c:59:31: error: ‘cf_string’ undeclared here (not in a function) 59 | {(char *)"guests_calias", cf_string, CA_STATIC, CA_PUBLIC, (int *)&,

Reconfigured with mail and comsys modules disabled and ran make again. Got this error:

alloc.c:224:11: error: conflicting types for ‘__xfind’ 224 | MEMTRACK *__xfind(void *ptr) | ^~~~~~~ alloc.c:176:12: note: previous implicit declaration of ‘__xfind’ was here 176 | mtrk = __xfind(ptr); | ^~~~~~~

**Comment by adamdray** [comment]
Lemme load a new 20.04 LTS server from linode and see.

Anything needed other than these?

apt-get update
apt install -y build-essential
apt install -y autoconf automake gdb git libffi-dev zlib1g-dev libssl-v
apt install -y make dh-autoreconf
apt install -y mlocate gcc cproto libpcre3 libpcre3-dev
apt install -y gdbm-l10n gdbmtool libgdbm-dev

**Comment by adamdray** [comment]
I see the "apt" comment in README.me now. Didn't see that before.

It built for me on 20.04 LTS. The old one was 20.10. I'll start a new 20.10 and see if there's an issue there.

**Comment by EddyBeaupre** [comment]
It should compile fine in 20.10. Just don't forget  to install all the needed packages.





Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-23 18 h 42 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Eddy Beaupré <eddy@beaupre.biz>, State change <state_change@noreply.github.com>
Objet : Re: [TinyMUSH/TinyMUSH] Building on Debian (#8)


I see the "apt" comment in README.me now. Didn't see that before.

It built for me on 20.04 LTS. The old one was 20.10. I'll start a new 20.10 and see if there's an issue there.
